"""Constants for AI Generation Engine."""

from enum import Enum


class SeverityLevel(str, Enum):
    """Severity levels for validation errors and warnings."""

    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


class ArtifactType(str, Enum):
    """Types of artifacts generated by the AI Generation Engine."""

    GENERATION_CONTEXT = "generation_context"
    STRATEGY = "strategy"
    COPY = "copy"
    IMAGE_PROMPT = "image_prompt"
    IMAGE = "image"
    VALIDATION = "validation"


class ValidationErrorCode(str, Enum):
    """Standard error codes for validation errors."""

    MISSING_REQUIRED_FIELD = "missing_required_field"
    INVALID_FORMAT = "invalid_format"
    EMPTY_VALUE = "empty_value"
    OUT_OF_RANGE = "out_of_range"
    CONFLICTING_VALUES = "conflicting_values"
    PLATFORM_UNSUPPORTED = "platform_unsupported"
    INCOMPLETE_CONTEXT = "incomplete_context"


class ValidationWarningCode(str, Enum):
    """Standard warning codes for validation warnings."""

    MISSING_RECOMMENDED_FIELD = "missing_recommended_field"
    SHORT_CONTENT = "short_content"
    MISSING_PLATFORM_ADAPTATION = "missing_platform_adaptation"
    MISSING_AUDIENCE_SEGMENTS = "missing_audience_segments"
    TOO_MANY_PLATFORMS = "too_many_platforms"
    MISSING_BRAND_VOICE = "missing_brand_voice"


class AssetType(str, Enum):
    """Types of assets that can be generated or manipulated."""

    HEADLINE = "headline"
    CAPTION = "caption"
    CTA = "cta"
    HASHTAG_SET = "hashtag_set"
    IMAGE = "image"
    METADATA = "metadata"
    OTHER = "other"
